baseURL = 'https://kikcode.github.io/'
languageCode = 'ko-kr'
title = 'Hello Kikcode'
theme = 'hugo-book'



[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'light'

  # css, js
  #custom_css = ["css/custom.css"]
  # custom_js = ["js/custom.js"]